### ISSUE TITLE
Project page: Next/Prev arrows

### ISSUE THREAD

**Issue by halfempty** [everythingtype/etc-nyc#15]
The arrows to the right allow you to move to the previous or next project. If you're coming from featured you'd get the featured next prev order. If you're in the everything section, it's that order. Doable?

Hovering over the arrow will replace the titling to the left with the project you would go to on click.

![image](https://cloud.githubusercontent.com/assets/775543/3405942/0896ebe4-fd85-11e3-8388-258b04b2c9ac.png)

**Comment by gehalber** [comment]
Ok. This is changing! Again! 
We want to place a "Next Project in the upper right corner which is fixed there like the nav. That way you can always click to the next project whenever you want.

![design-125](https://cloud.githubusercontent.com/assets/6076488/5617090/d58772aa-94d8-11e4-8401-26dd3fda1d84.jpg)

**Comment by halfempty** [comment]
@gehalber So I understand...

- The title is made smaller. Is it fixed?
- The "prev" arrow is removed
- The "next" arrow moves to the corner, changes to text, and is fixed?

**Comment by gehalber** [comment]
title is not fixed.

two other bullets are correct. 

Thanks!

**Comment by halfempty** [comment]
Okay, done!
